<?php

require_once dirname(__FILE__) . "/login_handler.php");

?>

<html>
    <head>
        <title>FIDO Main</title>
    </head>
    <body>
        <div class='container'>
            <?php
            // display the admin links if the logged in user was determined to be
            // a scheduler admin.
            if (isset($admin) && $admin) {
            ?>
            <div>
                <h2>Admin Pages</h2>
                <!--US139-->
                <a href='add_time_blocks.php'>Add Time Block</a>
                <!--TODO: add link for page generated by US140 -->
            </div>
            <?php
            }
            ?>
            <div>
                <!--US102, US128 is the submit handler for this page-->
                <h2>Student Pages</h2>
                <a href='Student/Student_submit_availability.php'>Submit Availability</a>
            </div>
        </div>
    </body>
</html>
